yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'password_reset/complete/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),

]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()
Group = 'Group'


class Post(models.Model):
    """Модель для хранения постов."""

    text = models.TextField(verbose_name='Описание',
                            help_text='Введите текст поста')
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата публикации')
    author = models.TextField(verbose_name='Автор')
    group = models.ForeignKey(
        Group,
        related_name='posts',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Группа',
        help_text='Группа к которой будет относится пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )

    class Meta:
        verbose_name = 'Alex Posting'
        verbose_name_plural = 'Alex Postings'
        ordering = ('-pub_date',)

    def __str__(self) -> str:
        return self.text


class Group(models.Model):
    """Модель для тематических сообществ пользователей."""

    title = models.CharField(max_length=200, verbose_name='Title')
    slug = models.SlugField(unique=True, verbose_name='Slug')
    description = models.TextField(verbose_name='Description')

    class Meta:
        verbose_name = 'Alex Group'
        verbose_name_plural = 'Alex Groups'

    def __str__(self) -> str:
        return self.title

yatube/posts/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')
        labels = {
            'text': 'Текст поста',
            'group': 'Группа поста',
        }
        help_texts = {
            'text': _('Заполните поле - для вашего поста'),
            'group': _('Группа не обязательна, но я настаиваю 😡')
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].widget.attrs['placeholder'] = (
            'Введите какой нибудь текст, ну пожалуйста 🥺'
        )
        self.fields['group'].empty_label = (
            'Выберите группу 👀'
        )

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm
from .models import Group, Post, User
from .utils import get_page_pages


def index(request):
    """Выводит шаблоны главной страницы."""
    context = get_page_pages(
        Post.objects.select_related('author', 'group'), request)
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """Выводит шаблон с группами постов."""
    group = get_object_or_404(Group, slug=slug)
    context = {
        'group': group,
    }
    context.update(get_page_pages(
        group.posts.select_related('author', 'group'), request))
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """Выводит шаблон профайла пользователя."""
    author = get_object_or_404(User, username=username)
    context = {
        'author': author,
    }
    context.update(get_page_pages(
        author.posts.all(), request))
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """Выводит информацию о посте."""
    post = get_object_or_404(Post.objects.select_related(
    ), id=post_id)
    context = {
        'post': post,
    }
    return render(request, 'posts/post_detail.html', context)


@ login_required
def post_create(request):
    """Создания новго поста."""
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        form.save()
        return redirect('posts:profile', request.user)
    return render(request, 'posts/post_create.html', {'form': form})


@ login_required
def post_edit(request, post_id):
    """Редактирование поста."""
    post = get_object_or_404(Post, id=post_id)
    is_edit = True
    if post.author != request.user:
        return redirect('posts:post_detail', post.pk)
    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    return render(request, 'posts/post_create.html', {'form': form,
                                                      'is_edit': is_edit})

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
  {% load static %}
  <h1 class="text-center">Привет, я Александр</h1>
  <br>
  <div class="text-center">
    <img src="{% static 'img/111.jpg' %}"
         width="200"
         height="200"
         alt="..."
         class="rounded">
  </div>
  <br>
  <p class="text-center">
    Тут я размещу инофрммцию о себе, используя свои умения верстатьbase.
    Картинки, блоки, элементы бустрап. А может быть, просто напишу несоклько абзацев текста.
  </p>
{% endblock %}

yatube/templates/about/tech.html
<!-- templates/about/tech.html -->
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
  {% comment %} Колонки с отступом сверху и снизу {% endcomment %}
  <div class="row">
    <h1>Вот что я умею</h1>
    {% comment %}
    Боковой блок со списком технологий 
    Займет всю ширину блока на мобильном
    и 25% при размерах экрана ≥768px
    {% endcomment %}
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Python</li>
        <li class="list-group-item">Django</li>
      </ul>
    </aside>
    {% comment %}
    Статья  
    Займет всю ширину блока на мобильном
    и 75% при размерах экрана ≥768px
    {% endcomment %}
    <article class="col-12 col-md-9">
      <p>
        Текст страницы "Технологии"
      </p>
    </article>
  </div>
{% endblock %}

yatube/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image" href="{% static "img/fav/fav.ico" %}">
    <link rel="apple-touch-icon"
          sizes="180x180"
          href="{% static "img/fav/apple-touch-icon.png" %}">
    <link rel="icon"
          type="image/png"
          sizes="32x32"
          href="{% static "img/fav/favicon-32x32.png" %}">
    <link rel="icon"
          type="image/png"
          sizes="16x16"
          href="{% static "img/fav/favicon-16x16.png" %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
      {% block title %}Последние обновления на сайте{% endblock %}
    </title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}Контент{% endblock %}
    </main>
    <footer>
      {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>
    © {{ year }} Copyright <span style="color:red">Ya</span>tube
  </p>
</footer>

yatube/templates/includes/form_errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}<div class="alert alert-danger">{{ error|escape }}</div>{% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}<div class="alert alert-danger">{{ error|escape }}</div>{% endfor %}
{% endif %}

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}"
           width="30"
           height="30"
           class="d-inline-block align-top"
           alt="">
      <span style="color:red">Ya</span>tube
    </a>
    {% with request.resolver_match.view_name as view_name %}
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
             href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item ">
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
             href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
               href="{% url 'posts:post_create' %}">Новая запись</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name  == 'users:password_change' %}active{% endif %}"
               href="{% url 'users:password_change'%}">Изменить пароль</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}"
               href="{% url 'users:logout'%}">Выйти</a>
          </li>
          <li class="nav-item navbar-text">Пользователь: {{ user.username }}</li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link link-light" href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light" href="{% url 'users:signup' %}">Регистрация</a>
          </li>
        {% endif %}
      </ul>
    {% endwith %}
  </div>
</nav>

yatube/templates/includes/one_post.html
<article>
<ul>
  <li>
    Автор:{{ post.author.get_full_name }}
    {% if post.author %}
      <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
    {% endif %}
  </li>
  <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
</ul>
<p>
  {{ post.text|linebreaks }}
</p>
{% if post.author %}
  <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
{% endif %}
</article>
{% if not group %}
  {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}
{% endif %}

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">Первая</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Записи сообщества {{ group.title }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>
      {{ group.description }}
    </p>
    {% for post in page_obj %}
      <article>
        {% include 'includes/one_post.html' %}
      </article>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block tittle %}Последние обновления на сайте{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Последние обновления на сайте</h1>
    {% for post in page_obj %}
      {% include 'includes/one_post.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/post_create.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block content %}
  {% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header"></div>
        {% if is_edit %}
          Редактировать пост
        {% else %}
          Новый пост
        {% endif %}
        <div class="card-body">
          {% include 'includes/form_errors.html' %}
          <form method="post"
            {% if action_url %} action=" {% if post %} {% url 'posts:post_edit' %} {% else %} {% url 'posts:post_create' %} {% endif %}"
          {% endif %}>
          {% csrf_token %}
          {% for field in form %}
            <div class="form-group row my-3"
                 {% if field.field.required %} aria-required="true" {% else %} aria-required="false" {% endif %}>
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}
              </label>
              <div>
                {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">
              {% if is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %}
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Пост: {{ post.text|truncatechars:30 }}{% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group.title }}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          </li>
        {% endif %}
        <li class="list-group-item">Автор: {{ post.author.get_full_name }}</li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{post.author.posts.count}}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>
        {{ post.text|linebreaks }}
      </p>
      {% if request.user == post.author %}
        <a class="btn btn-primary"
           href="{% url 'posts:post_edit' post_id=post.id %}">Редактировать</a>
      {% endif %}
    </article>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Профайл пользователя {{ author.username }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Все посты пользователя {{ author.username }}</h1>
    <h3>Всего постов: {{ author.posts.count }}</h3>
    {% for post in page_obj %}
      <article>
        <ul>
          {% if  not author %}<li>Автор: {{ post.author.get_full_name }}</li>{% endif %}
          <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
        </ul>
        <p>
          {{ post.text|linebreaks }}
        </p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
      </article>
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Выход</div>
        <div class="card-body">
          <p>
            Вы вышли из своей учётной записи. Ждём вас снова!
          </p>
        </div>
        <!-- card body -->
      </div>
      <!-- card -->
    </div>
    <!-- col -->
  </div>
  <!-- row -->
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
  {% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Войти на сайт</div>
        <div class="card-body">
          {% include 'includes/form_errors.html' %}
          <form method="post"
                {% if action_url %} action="{% url action_url %}" {% endif %}>
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row my-3"
                   {% if field.field.required %} aria-required="true" {% else %} aria-required="false" {% endif %}>
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}
                </label>
                <div>
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">Войти</button>
              <a href="{% url 'users:signup' %}" class="btn btn-link">Забыли пароль?</a>
            </div>
          </form>
        </div>
        <!-- card body -->
      </div>
      <!-- card -->
    </div>
    <!-- col -->
  </div>
  <!-- row -->
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}Пароль изменен{% endblock %}
{% block content %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Пароль изменён
              </div>
              <div class="card-body"> 
                <p>Пароль изменён успешно</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Изменение пароля{% endblock %}
{% block content %}
  {% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Изменить пароль</div>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row"
                   aria-required
                   {% if field.field.required %}"true"{% else %}"false"{% endif %}>
                <label for="{{ field.id_for_label }}"
                       class="col-md-4 col-form-label text-md-right">
                  {{ field.label }}
                  {% if field.field.required %}<span class="required">*</span>{% endif %}
                </label>
                <div class="col-md-6">
                  {{ field|addclass:"form-control" }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
            <!-- <div class="col-md-6 offset-md-4"> -->
            <div class="border-top text-center py-3">
              <button type="submit" class="btn btn-primary">Изменить пароль</button>
            </div>
          </form>
        </div>
        <!-- card body -->
      </div>
      <!-- card -->
    </div>
    <!-- col -->
  </div>
  <!-- row -->
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">Восстановление пароля завершено</div>
          <div class="card-body">
            <p>
              Ваш пароль был сохранен. Используйте его для входа
            </p>
            <a href="../users/login.html">войти</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% block content %}

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Пароль изменен{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">Введите новый пароль</div>
          <div class="card-body">
            <form method="post" >
              {% csrf_token %}
              <input type="hidden" name="csrfmiddlewaretoken" value="">
              <div class="form-group row my-3 p-3">
                <label for="id_new_password1">
                  Новый пароль
                  <span class="required text-danger">*</span>
                </label>
                <input type="password"
                       name="new_password1"
                       class="form-control"
                       required
                       id="id_new_password1">
                <small id="id_new_password1-help" class="form-text text-muted">
                  <ul>
                    <li>
                      Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.
                    </li>
                    <li>Ваш пароль должен содержать как минимум 8 символов.</li>
                    <li>Ваш пароль не может быть одним из широко распространённых паролей.</li>
                    <li>Ваш пароль не может состоять только из цифр.</li>
                  </ul>
                </small>
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_new_password2">
                  Подтверждение нового пароля
                  <span class="required text-danger">*</span>
                </label>
                <input type="password"
                       name="new_password2"
                       class="form-control"
                       required
                       id="id_new_password2">
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">Назначить новый пароль</button>
              </div>
            </form>
          </div>
          <!-- card body -->
        </div>
        <!-- card -->
      </div>
      <!-- col -->
    </div>
    <!-- row -->
    <!-- если использована неправильная ссылка -->
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">Ошибка</div>
          <div class="card-body">
            <p>
              Ссылка сброса пароля содержит ошибку или устарела.
            </p>
          </div>
          <!-- card body -->
        </div>
        <!-- card -->
      </div>
      <!-- col -->
    </div>
    <!-- row -->
    <!-- конец если использована неправильная ссылка -->
  </div>
{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}Сброс пароля{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">Отправлено письмо</div>
          <div class="card-body">
            <p>
              Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}Сброс пароля{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
          </div>
          <div class="card-body">
            <form method="post" >
                {% csrf_token %}
              <input type="hidden" name="csrfmiddlewaretoken" value="">
              <div class="form-group row my-3 p-3">
                <label for="id_email">
                  Адрес электронной почты
                  <span class="required text-danger">*</span>
                </label>
                <input type="email"
                       name="email"
                       maxlength="254"
                       class="form-control"
                       required
                       id="id_email">
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">Сбросить пароль</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
        <div class="card-body">
          {% include 'includes/form_errors.html' %}
          <form method="post" action="{% url 'users:signup' %}">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}
                </label>
                {{ field }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                {% endif %}
              </div>
            {% endfor %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
            </div>
          </form>
        </div>
        <!-- card body -->
      </div>
      <!-- card -->
    </div>
    <!-- col -->
  </div>
  <!-- row -->
{% endblock %}